version: '3'
services:
  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    depends_on:
      - todoback
    restart: always
    environment:
      - REACT_APP_API_HOST=todoback
      - REACT_APP_API_PORT=3001
  todoback:
    image: todobackend
    ports:
      - 3001:3001
    restart: always
  todotests:
    image: todotests
    depends_on:
      - todofront
      - todoback
    restart: always 
    environment:
      - FRONT_HOST=todofront
      - FRONT_PORT=3000