version: '3'
services:
  todofront:
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
  todoback:
    ports:
      - 3001:3001
  todotests:
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofrontend